services:
  dashboard:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  notificador:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8889:8889"
    restart: unless-stopped

  relay:
    build: ./relay
    ports:
      - "8888:8888"
    restart: unless-stopped
